title: It's machine learnin' time
author: Jason Close
email: willoughby@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site for discussing data science and machine learning endeavors, serving up original educational materials and blogging about miscellany.

twitter_username: garbantho
github_username:  jcclose1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - nonprofit.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
